# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-2048-ss
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: 208409385559.dkr.ecr.eu-central-1.amazonaws.com/react-app-2048-ss:latest
          ports:
            - containerPort: 3000